name: Notify users based on issue labels

on:
  issues:
    types: [labeled]
# TODO: Speak to Sean @seanmcilroy29 about SENDGRID_API_KEY (100 a day is free)
jobs:
  notify:
    runs-on: ubuntu-latest
    steps:
    - uses: timheuer/issue-notifier@v1
      env:
        SENDGRID_API_KEY: ${{ secrets.SENDGRID_API_KEY }}
      with:
        fromMailAddress: 'chris.lloyd-jones@avanade.com' #'no-reply@greensoftware.foundation'
        toMailAddress: 'chris.lloyd-jones@avanade.com'#'standards-wg@greensoftware.foundation'
        subject: 'A new issue was labeled for RNA'
        labelsToMonitor: 'minor-0,minor-1,minor-2,medium,major-5,major-3,consistency-14'
# TODO: Check labels with @atg-abhishek
# TODO: Check from/to addresses with @seanmcilroy29