name: Invite users to add to citation files

on: [issues, pull_request]

jobs:
  invitation:
    runs-on: ubuntu-latest
      steps:
      - uses: actions/first-interaction@v1
        with:
          repo-token: ${{ secrets.GITHUB_TOKEN }}
          issue-message: '### Thanks for your first issue!\n\nIf you haven't already done so, please feel free to add your name to the [citation file](https://github.com/Green-Software-Foundation/software_carbon_intensity/blob/dev/CITATION.cff) in the repository via Pull Request. For more information on the file format, see [https://citation-file-format.github.io/](https://citation-file-format.github.io/).'
          pr-message: '### Thanks for your first issue!\n\nIf you haven't already done so, please feel free to add your name to the [citation file](https://github.com/Green-Software-Foundation/software_carbon_intensity/blob/dev/CITATION.cff) in the repository via Pull Request. For more information on the file format, see [https://citation-file-format.github.io/](https://citation-file-format.github.io/).'